
NUMBER_OF_INTEGRATION_POINTS = 4
DEBUG = False
SAVE_TO_CSV = True
PLOT_RESULTS = True
ENTIRE_RADIATOR_HAS_DERICHLET_BC = False # If False, only the top face has Dirichlet BC
MULTIPROCESSING_ENABLED = False
MAX_PROCESSES = 4
PLOT_SAVE_INTERVAL = 1.0